version: "3"
services:
  auth:
    build: ./auth-service
    ports:
      - "3001:3000"

  product:
    build: ./product-service
    ports:
      - "3002:3000"

  notify:
    build: ./notification-service
    ports:
      - "3003:3000"
